<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1527393271384" stop="1527393271415">
  <name>test_001</name>
  <labels/>
  <test-cases>
    <test-case start="1527393271384" status="passed" stop="1527393271384">
      <name>Test_001.test01[1]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="3348-MainThread"/>
        <label name="host" value="DESKTOP-BCHJMCJ"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1527393271384" status="failed" stop="1527393271415">
      <name>Test_001.test01[2]</name>
      <failure>
        <message>AssertionError: assert 2 != 2</message>
        <stack-trace>self = &lt;test_001.Test_001 object at 0x060A7090&gt;, a = 2

    @pytest.mark.parametrize('a',[1,2,3])
    def test01(self,a):
&gt;       assert a !=2
E       assert 2 != 2

scripts\test_001.py:7: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="3348-MainThread"/>
        <label name="host" value="DESKTOP-BCHJMCJ"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1527393271415" status="passed" stop="1527393271415">
      <name>Test_001.test01[3]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="3348-MainThread"/>
        <label name="host" value="DESKTOP-BCHJMCJ"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
